### ISSUE TITLE
values returned by get_gmtime function are volitable and may become invalid over time

### ISSUE THREAD

**Issue by Roietronics** [Avnet/mbedv5_azure_iot_sdk#26]
The implementation of the get_gmtime function in the platform/agenttime_mbed.c file  allocate a local copy of a tm structure which it then passes to the gmtime_r to be filled in and then returns a pointer to that structure to the caller.  Since the tm structure is a function local variable, it scope Is local to the function and it will have been allocated on the stack.  Then the get_gmtime function returns to its caller the stack pointer returned to it pre call value and the it caller will now be hold a pointer to a block of memory containing the tm structure which is located on the thread's stack below the current location pointer to by the thread's stack pointer.  The next time the thread's code makes a function call some or all of the data in the tm structure will most likely be overwritten.

Switching to a tm structure allocated from the heap would solve the volatility problem but introduces a high risk for memory leaks since the responsibility for deallocation the memory block holding the tm structure resides with the get_gmtime caller which was not the allocator of the memory block.

The ideal solution to this problem requires the ability to some how create statically allocated objects which are owned a specific thread.

Microsoft solution for this problem in the Windows world was the concept of Thread Local Storage (TLS)  blocks of memory which are owned by a specific thread.

**Comment by jflynn129** [comment]
good catch, I obviously didn't catch it and didn't have anyone to peer-review the code for me. I'll fix it with placing a static infront of the declaration.  that will fix the auto problem but of course it doesn't address the thread-safe aspect.  To do that, the function would have to implement a TLS mechanism like you mention.
